/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pptls;

/**
 *
 * @author david
 */
public class frmPPTLS extends javax.swing.JFrame {

    int piedra,papel,tijera,lagarto,spock,aleatorio;
    public frmPPTLS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnspock = new javax.swing.JButton();
        btnpiedra = new javax.swing.JButton();
        btnpapel = new javax.swing.JButton();
        btnlagarto = new javax.swing.JButton();
        btntijera = new javax.swing.JButton();
        btnjugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnspock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pptls/spock_1.jpg"))); // NOI18N
        btnspock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspockActionPerformed(evt);
            }
        });

        btnpiedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pptls/piedra.jpg"))); // NOI18N
        btnpiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpiedraActionPerformed(evt);
            }
        });

        btnpapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pptls/papel.jpg"))); // NOI18N
        btnpapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpapelActionPerformed(evt);
            }
        });

        btnlagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pptls/lagarto.jpg"))); // NOI18N
        btnlagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlagartoActionPerformed(evt);
            }
        });

        btntijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pptls/tijera.jpg"))); // NOI18N
        btntijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntijeraActionPerformed(evt);
            }
        });

        btnjugar.setText("Jugar");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        jLabel1.setText("PPTLS");

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnpiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnpapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btntijera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnlagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnspock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnjugar))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpapel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntijera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnspock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnjugar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        txtResultado.append("Inicia el juego\n");

    }//GEN-LAST:event_formWindowOpened

    private void btnpiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpiedraActionPerformed
        txtResultado.setText("");
        txtResultado.append("Piedra\n");
        txtResultado.append("vs\n");
        aleatorio=(int)(Math.random()*5+1);
        System.out.print(aleatorio);
        if(piedra==aleatorio){
          txtResultado.append("Piedra\n");
          txtResultado.append("Empate\n");
        }
        if(papel==aleatorio){
          txtResultado.append("Papel\n");
          txtResultado.append("Perdiste\n");            
        }
        if(tijera==aleatorio){
          txtResultado.append("Tijera\n");
          txtResultado.append("Ganaste\n");       
        }
        if(lagarto==aleatorio){
          txtResultado.append("Lagarto\n");
          txtResultado.append("Ganaste\n");     
        }
        if(spock==aleatorio){
          txtResultado.append("spock\n");
          txtResultado.append("Perdiste\n");      
        }
    }//GEN-LAST:event_btnpiedraActionPerformed

    private void btnpapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpapelActionPerformed
        txtResultado.setText("");
        txtResultado.append("Papel\n");
        txtResultado.append("vs\n");
                
        if(papel==aleatorio){
          txtResultado.append("Papel\n");
          txtResultado.append("Empate\n");                
        }
        if(piedra==aleatorio){
          txtResultado.append("Piedra\n");
          txtResultado.append("Ganaste\n");       
        }
        if(tijera==aleatorio){
          txtResultado.append("Tijera\n");
          txtResultado.append("Perdiste\n");       
        }
        if(lagarto==aleatorio){
          txtResultado.append("Lagarto\n");
          txtResultado.append("Ganaste\n");     
        }
        if(spock==aleatorio){
          txtResultado.append("Spock\n");
          txtResultado.append("Perdiste\n");      
        }
    }//GEN-LAST:event_btnpapelActionPerformed

    private void btntijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntijeraActionPerformed
        txtResultado.setText("");
        txtResultado.append("Tijera\n");
        txtResultado.append("vs\n");
                
        if(tijera==aleatorio){
          txtResultado.append("Tijera\n");
          txtResultado.append("Empate\n");                
        }
        if(papel==aleatorio){
          txtResultado.append("Papel\n");
          txtResultado.append("Ganaste\n");       
        }
        if(piedra==aleatorio){
          txtResultado.append("Piedra\n");
          txtResultado.append("Perdiste\n");       
        }
        if(lagarto==aleatorio){
          txtResultado.append("Lagarto\n");
          txtResultado.append("Ganaste\n");     
        }
        if(spock==aleatorio){
          txtResultado.append("Spock\n");
          txtResultado.append("Perdiste\n");      
        }
    }//GEN-LAST:event_btntijeraActionPerformed

    private void btnlagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlagartoActionPerformed
        txtResultado.setText("");
        txtResultado.append("Lagarto\n");
        txtResultado.append("vs\n");
                
        if(lagarto==aleatorio){
          txtResultado.append("Lagarto\n");
          txtResultado.append("Empate\n");                
        }
        if(papel==aleatorio){
          txtResultado.append("Papel\n");
          txtResultado.append("Ganaste\n");       
        }
        if(tijera==aleatorio){
          txtResultado.append("Tijera\n");
          txtResultado.append("Perdiste\n");       
        }
        if(piedra==aleatorio){
          txtResultado.append("Piedra\n");
          txtResultado.append("Perdiste\n");     
        }
        if(spock==aleatorio){
          txtResultado.append("Spock\n");
          txtResultado.append("Ganaste\n");      
        }
    }//GEN-LAST:event_btnlagartoActionPerformed

    private void btnspockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspockActionPerformed
        txtResultado.setText("");
        txtResultado.append("Spock\n");
        txtResultado.append("vs\n");
                
        if(spock==aleatorio){
          txtResultado.append("Spock\n");
          txtResultado.append("Empate\n");                
        }
        if(papel==aleatorio){
          txtResultado.append("Papel\n");
          txtResultado.append("Perdiste\n");       
        }
        if(tijera==aleatorio){
          txtResultado.append("Tijera\n");
          txtResultado.append("Ganaste\n");       
        }
        if(lagarto==aleatorio){
          txtResultado.append("Lagarto\n");
          txtResultado.append("Perdiste\n");     
        }
        if(piedra==aleatorio){
          txtResultado.append("Piedra\n");
          txtResultado.append("Ganaste\n");      
        }
    }//GEN-LAST:event_btnspockActionPerformed

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        piedra=1;
        papel=2;
        tijera=3;
        lagarto=4;
        spock=5;
    }//GEN-LAST:event_btnjugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPPTLS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPPTLS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton btnlagarto;
    private javax.swing.JButton btnpapel;
    private javax.swing.JButton btnpiedra;
    private javax.swing.JButton btnspock;
    private javax.swing.JButton btntijera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
